# Generated by Django 6.1.1 on 2026-09-24 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('SURVEY', 'Survey Report'), ('TEMPORAL', 'Temporal Intelligence Report'), ('EVALUATION', 'Evaluation Report')], default='SURVEY', max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('parameters', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='surveys.survey')),
            ],
            options={
                'db_table': 'sonarx_reports',
                'ordering': ['-timestamp'],
            },
        ),
    ]
