# Generated by Django 6.1.1 on 2026-09-24 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sonar', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebrisObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debris_uid', models.CharField(max_length=20, unique=True)),
                ('first_observed', models.DateTimeField(auto_now_add=True)),
                ('last_observed', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('STILL_PRESENT', 'Still Present'), ('NOT_DETECTED', 'Not Detected'), ('POTENTIALLY_RELOCATED', 'Potentially Relocated'), ('POSSIBLE_MATCH', 'Possible Match'), ('NEW_DETECTION', 'New Detection'), ('REQUIRES_VERIFICATION', 'Requires Verification')], default='NEW_DETECTION', max_length=25)),
                ('classification', models.CharField(blank=True, max_length=25)),
                ('hazard_level', models.CharField(default='NONE', max_length=15)),
                ('is_demo', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sonarx_debris_objects',
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detection_uid', models.CharField(blank=True, max_length=30, unique=True)),
                ('classification', models.CharField(choices=[('MARINE_DEBRIS', 'Marine Debris'), ('NATURAL_FORMATION', 'Natural Formation'), ('SONAR_ARTIFACT', 'Sonar Artifact'), ('UNKNOWN_ANOMALY', 'Unknown Anomaly')], default='UNKNOWN_ANOMALY', max_length=25)),
                ('confidence', models.FloatField(default=0.0, help_text='Prototype evidence score 0-100')),
                ('evidence_score', models.FloatField(default=0.0)),
                ('false_positive_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('bbox_x', models.IntegerField(blank=True, null=True)),
                ('bbox_y', models.IntegerField(blank=True, null=True)),
                ('bbox_w', models.IntegerField(blank=True, null=True)),
                ('bbox_h', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('coordinate_source', models.CharField(blank=True, help_text='Source of coordinate estimate', max_length=50)),
                ('coordinate_note', models.TextField(blank=True)),
                ('hazard_level', models.CharField(choices=[('NONE', 'None'), ('CAUTION', 'Caution'), ('HIGH_CAUTION', 'High Caution')], default='NONE', max_length=15)),
                ('hazard_score', models.FloatField(default=0.0)),
                ('hazard_indicators', models.JSONField(default=list)),
                ('hazard_limited_data', models.BooleanField(default=False)),
                ('recommended_action', models.TextField(blank=True)),
                ('supporting_evidence', models.JSONField(default=list)),
                ('counter_evidence', models.JSONField(default=list)),
                ('inference_mode', models.CharField(choices=[('DEMO', 'Demo Mode'), ('CLASSICAL_CV', 'Classical CV Fallback'), ('YOLO', 'YOLO Model')], default='DEMO', max_length=15)),
                ('data_source', models.CharField(default='DEMO', max_length=10)),
                ('processing_summary', models.JSONField(default=dict)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('CLASS_CHANGED', 'Class Changed by Reviewer')], default='PENDING', max_length=15)),
                ('reviewer_class', models.CharField(blank=True, help_text='Class assigned by reviewer', max_length=25)),
                ('debris_uid', models.CharField(blank=True, max_length=20)),
                ('temporal_status', models.CharField(blank=True, max_length=25)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sonar_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='sonar.sonarfile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='surveys.survey')),
            ],
            options={
                'db_table': 'sonarx_detections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hazard_level', models.CharField(default='NONE', max_length=15)),
                ('classification', models.CharField(blank=True, max_length=25)),
                ('confidence', models.FloatField(default=0.0)),
                ('fingerprint_snapshot', models.JSONField(default=dict)),
                ('debris_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='detections.debrisobject')),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='detections.detection')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
            options={
                'db_table': 'sonarx_detection_observations',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SonarFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backscatter_score', models.FloatField(default=0.0)),
                ('backscatter_status', models.CharField(choices=[('STRONG', 'Strong'), ('MODERATE', 'Moderate'), ('WEAK', 'Weak'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=15)),
                ('texture_score', models.FloatField(default=0.0)),
                ('texture_status', models.CharField(choices=[('STRONG', 'Strong'), ('MODERATE', 'Moderate'), ('WEAK', 'Weak'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=15)),
                ('geometry_score', models.FloatField(default=0.0)),
                ('geometry_status', models.CharField(choices=[('STRONG', 'Strong'), ('MODERATE', 'Moderate'), ('WEAK', 'Weak'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=15)),
                ('shadow_score', models.FloatField(default=0.0)),
                ('shadow_status', models.CharField(choices=[('STRONG', 'Strong'), ('MODERATE', 'Moderate'), ('WEAK', 'Weak'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=15)),
                ('object_shadow_score', models.FloatField(default=0.0)),
                ('object_shadow_status', models.CharField(choices=[('STRONG', 'Strong'), ('MODERATE', 'Moderate'), ('WEAK', 'Weak'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=15)),
                ('seabed_context_score', models.FloatField(default=0.0)),
                ('seabed_context_status', models.CharField(choices=[('STRONG', 'Strong'), ('MODERATE', 'Moderate'), ('WEAK', 'Weak'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=15)),
                ('signal_quality_score', models.FloatField(default=0.0)),
                ('signal_quality_status', models.CharField(choices=[('STRONG', 'Strong'), ('MODERATE', 'Moderate'), ('WEAK', 'Weak'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=15)),
                ('evidence_score', models.FloatField(default=0.0)),
                ('raw_features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='detections.detection')),
            ],
            options={
                'db_table': 'sonarx_fingerprints',
            },
        ),
        migrations.CreateModel(
            name='TemporalMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('fingerprint_similarity', models.FloatField(blank=True, help_text='Fingerprint Similarity Score — not a probability', null=True)),
                ('status', models.CharField(choices=[('STILL_PRESENT', 'Still Present'), ('NOT_DETECTED', 'Not Detected'), ('POTENTIALLY_RELOCATED', 'Potentially Relocated'), ('POSSIBLE_MATCH', 'Possible Match'), ('REQUIRES_VERIFICATION', 'Requires Verification')], max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_comment', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_candidate', to='detections.detectionobservation')),
                ('debris_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_matches', to='detections.debrisobject')),
                ('previous_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_previous', to='detections.detectionobservation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporal_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sonarx_temporal_matches',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CLASS_CHANGED', 'Classification Changed'), ('ESCALATED', 'Escalated'), ('HAZARD_CONFIRMED', 'Hazard Confirmed'), ('HAZARD_DOWNGRADED', 'Hazard Downgraded')], max_length=20)),
                ('new_class', models.CharField(blank=True, max_length=25)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='detections.detection')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sonarx_verifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
