# Generated by Django 6.1.1 on 2026-09-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='temporal_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
