# Generated by Django 6.1.1 on 2026-09-24 06:45

import django.db.models.deletion
import sonar.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonarFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to=sonar.models.sonar_upload_path)),
                ('demo_image_key', models.CharField(blank=True, help_text='Key for bundled demo images', max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PNG', 'PNG Image'), ('JPG', 'JPEG Image'), ('TIFF', 'TIFF Image'), ('DEMO', 'Demo Synthetic Image')], default='PNG', max_length=10)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_grayscale', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALID', 'Valid'), ('WARNING', 'Valid with Warnings'), ('INVALID', 'Invalid'), ('PREPROCESSING', 'Preprocessing'), ('PREPROCESSED', 'Preprocessed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('range_scale_mpp', models.FloatField(blank=True, null=True)),
                ('pixel_scale_gpp', models.FloatField(blank=True, help_text='Ground range per pixel after correction', null=True)),
                ('channel_layout', models.CharField(choices=[('PORT', 'Port'), ('STARBOARD', 'Starboard'), ('BOTH', 'Both'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('already_gain_corrected', models.BooleanField(blank=True, null=True)),
                ('already_slant_range_corrected', models.BooleanField(blank=True, null=True)),
                ('already_processed', models.BooleanField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('quality_level', models.CharField(blank=True, max_length=20)),
                ('saturation_ratio', models.FloatField(blank=True, null=True)),
                ('dropout_ratio', models.FloatField(blank=True, null=True)),
                ('snr_proxy', models.FloatField(blank=True, null=True)),
                ('nadir_width_px', models.IntegerField(blank=True, null=True)),
                ('image_contrast', models.FloatField(blank=True, null=True)),
                ('usable_area_ratio', models.FloatField(blank=True, null=True)),
                ('processed_file', models.ImageField(blank=True, null=True, upload_to='sonar_processed/')),
                ('is_demo', models.BooleanField(default=False)),
                ('data_source', models.CharField(default='SURVEY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonar_files', to='surveys.survey')),
            ],
            options={
                'db_table': 'sonarx_sonar_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('INGESTION', 'Data Ingestion'), ('VALIDATION', 'Validation'), ('NADIR', 'Nadir Gap Handling'), ('GAIN', 'Gain Correction'), ('SLANT_RANGE', 'Slant-Range Correction'), ('NOISE', 'Noise Reduction'), ('CONTRAST', 'Contrast Enhancement'), ('QUALITY', 'Quality Assessment'), ('DETECTION', 'Candidate Detection'), ('FINGERPRINT', 'Sonar Fingerprint'), ('FUSION', 'Evidence Fusion'), ('CLASSIFICATION', 'Classification'), ('HAZARD', 'Hazard Assessment'), ('GEOLOCATION', 'Geolocation'), ('TEMPORAL', 'Temporal Tracking')], max_length=30)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('ESTIMATED', 'Estimated'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed'), ('COMPLETE', 'Complete'), ('NOT_APPLIED', 'Not Applied')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
                ('software_version', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='sonar.sonarfile')),
            ],
            options={
                'db_table': 'sonarx_processing_logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Valid with Warnings'), ('INVALID', 'Invalid')], max_length=10)),
                ('checks', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('saturation_ratio', models.FloatField(blank=True, null=True)),
                ('dropout_ratio', models.FloatField(blank=True, null=True)),
                ('nadir_detected', models.BooleanField(blank=True, null=True)),
                ('signal_quality', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='sonar.sonarfile')),
            ],
            options={
                'db_table': 'sonarx_validation_results',
            },
        ),
    ]
