# Generated by Django 6.1.1 on 2026-09-24 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('area', models.CharField(blank=True, max_length=200)),
                ('operator', models.CharField(blank=True, max_length=200)),
                ('data_source', models.CharField(choices=[('DEMO', 'Demo Data'), ('SURVEY', 'Real Survey Data')], default='SURVEY', max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('PREPROCESSING', 'Preprocessing'), ('PREPROCESSED', 'Preprocessed'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('altitude_m', models.FloatField(blank=True, help_text='Altitude above seabed in metres', null=True)),
                ('range_scale_mpp', models.FloatField(blank=True, help_text='Slant-range scale: metres per pixel', null=True)),
                ('channel_layout', models.CharField(choices=[('PORT', 'Port'), ('STARBOARD', 'Starboard'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('already_gain_corrected', models.BooleanField(default=False)),
                ('already_slant_range_corrected', models.BooleanField(default=False)),
                ('already_processed', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sonarx_surveys',
                'ordering': ['-created_at'],
            },
        ),
    ]
